name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 2.0.3
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: 'none'


environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
  csv: ^4.0.3
  recase: ^3.0.0
  code_builder: ^3.2.0
  dart_style: ^1.3.8+1 
  source_gen: ^0.9.8
  
  build: ^1.5.0
  analyzer: ^0.40.5
  collection: ^1.14.11
  intl: ^0.16.1

  flutter_sheet_localization:
    git: 
      url: https://github.com/NiKoTron/flutter_sheet_localization.git
      ref: update_deps
      path: flutter_sheet_localization/

dev_dependencies:
  build_test: ^1.2.2
  build_runner: ^1.10.4
